name: CI

on: [push, pull_request]
jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # checkout project from git
      - uses: actions/setup-node@v3 # install node 
      - name: Install dependencies #  go to project and install dependencies from json
        run: cd web/new_project && npm ci #
      - name: Install playwright browsers # 
        run: npx playwright install --with-deps
     # - name: Run app
     #   run: npm run serve
     #   working-directory: web/new_project
      - name: Run tests
        run: cd web/new_project/tests/unit && npm run test:unit 

